window.customCsvData =`name,type1,type2,generation,filters,banFilter,styleForm,link
バジリール,くさ,でんき,PD,一般/御三家,,,https://w.atwiki.jp/altair1/pages/683.html
コマレオン,ほのお,じめん,PD,一般/御三家,,,https://w.atwiki.jp/altair1/pages/686.html
バクソウオ,みず,ゴースト,PD,一般/御三家,,,https://w.atwiki.jp/altair1/pages/689.html
カピランド,ノーマル,,PD,一般,,,https://w.atwiki.jp/altair1/pages/691.html
タワラビー,ノーマル,,PD,一般,,,https://w.atwiki.jp/altair1/pages/693.html
トンビート,ノーマル,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/696.html
ドンカング,ノーマル,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/699.html
ダンパイア,あく,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/701.html
ゼバトル,みず,じめん,PD,入手不可,,,https://w.atwiki.jp/altair1/pages/703.html
ライチュウ,でんき,,初代,一般,,,https://w.atwiki.jp/altair1/pages/706.html
ゴリチュウ,でんき,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/707.html
モクヨーテ,くさ,かくとう,PD,一般,,,https://w.atwiki.jp/altair1/pages/708.html
フローリア,こおり,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/711.html
メラザード,ほのお,かくとう,PD,一般,,,https://w.atwiki.jp/altair1/pages/714.html
フラバニー,くさ,,PD,一般,,,https://w.atwiki.jp/altair1/pages/716.html
セラーナ,くさ,,AS,一般,,,https://w.atwiki.jp/altair1/pages/718.html
プウガム,フェアリー,ノーマル,PD,一般,,,https://w.atwiki.jp/altair1/pages/720.html
ハタラクマ,ノーマル,,PD,一般,,,https://w.atwiki.jp/altair1/pages/722.html
ペガーン,エスパー,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/724.html
ユニサス,エスパー,はがね,AS,一般,,,https://w.atwiki.jp/altair1/pages/725.html
アスイーツ,こおり,,ベガ,一般,,輝石,https://w.atwiki.jp/altair1/pages/726.html
プリモード,こおり,フェアリー,PD,一般,,,https://w.atwiki.jp/altair1/pages/727.html
レネモード,こおり,でんき,PD,一般,,,https://w.atwiki.jp/altair1/pages/729.html
メタゲラス,はがね,じめん,AS,一般,,,https://w.atwiki.jp/altair1/pages/731.html
アブソル,あく,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/732.html
ディザソル,あく,,AS,一般,,,https://w.atwiki.jp/altair1/pages/733.html
キリンリキ,ノーマル,エスパー,金銀,一般,,輝石,https://w.atwiki.jp/altair1/pages/734.html
フォリキー,ノーマル,エスパー,AS,一般,,,https://w.atwiki.jp/altair1/pages/735.html
ファントマ,ほのお,,AS,一般,,,https://w.atwiki.jp/altair1/pages/737.html
ジャンボス,かくとう,,PD,一般,,,https://w.atwiki.jp/altair1/pages/740.html
ロクナイト,いわ,,PD,一般,,,https://w.atwiki.jp/altair1/pages/743.html
ザングース,ノーマル,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/744.html
マビュート,ノーマル,あく,PD,一般,,,https://w.atwiki.jp/altair1/pages/745.html
ハブネーク,どく,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/746.html
ジャベット,どく,あく,PD,一般,,,https://w.atwiki.jp/altair1/pages/747.html
ググズリー,ノーマル,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/749.html
ハンタマ,ゴースト,かくとう,AS,入手不可,,,https://w.atwiki.jp/altair1/pages/750.html
シャクゾラ,むし,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/753.html
ベノレート,むし,どく,PD,一般,,,https://w.atwiki.jp/altair1/pages/756.html
マーダラー,みず,あく,PD,一般,,,https://w.atwiki.jp/altair1/pages/758.html
スルドイカ,みず,いわ,PD,一般,,,https://w.atwiki.jp/altair1/pages/760.html
マルマジロ,いわ,はがね,AS,一般,,,https://w.atwiki.jp/altair1/pages/762.html
リーフィス,くさ,みず,AS,一般,,,https://w.atwiki.jp/altair1/pages/764.html
エアームド,はがね,ひこう,金銀,一般,,輝石,https://w.atwiki.jp/altair1/pages/765.html
エアメイル,はがね,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/766.html
バフォット,はがね,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/769.html
トロピウス,くさ,ひこう,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/770.html
フルティウス,くさ,ドラゴン,PD,一般,,,https://w.atwiki.jp/altair1/pages/771.html
フィニクス,ほのお,ドラゴン,AS,一般,,,https://w.atwiki.jp/altair1/pages/774.html
コクジャク,ゴースト,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/776.html
コーシャン,ほのお,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/778.html
ボルトック,でんき,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/780.html
テペトラー,みず,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/782.html
ロップル,ゴースト,エスパー,AS,入手不可,,,https://w.atwiki.jp/altair1/pages/783.html
オタクン,どく,,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/784.html
ネラー,あく,,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/785.html
ニートン,ゴースト,,AS,一般,,,https://w.atwiki.jp/altair1/pages/786.html
スナンクス,じめん,,PD,一般,,,https://w.atwiki.jp/altair1/pages/788.html
ハクタクン,エスパー,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/789.html
カマフラー,むし,くさ,PD,一般,,,https://w.atwiki.jp/altair1/pages/790.html
ボルボット,はがね,,PD,一般,,,https://w.atwiki.jp/altair1/pages/793.html
ボルテフ,でんき,ひこう,PD,入手不可,,,https://w.atwiki.jp/altair1/pages/794.html
スピネルス,いわ,ドラゴン,PD,一般,,,https://w.atwiki.jp/altair1/pages/796.html
イバチラス,いわ,みず,PD,一般,,,https://w.atwiki.jp/altair1/pages/798.html
マカドゥス,いわ,でんき,AS,一般,,,https://w.atwiki.jp/altair1/pages/800.html
プテリクス,いわ,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/802.html
ビャクガー,こおり,でんき,PD,一般,,,https://w.atwiki.jp/altair1/pages/805.html
コファルド,こおり,あく,PD,一般,,,https://w.atwiki.jp/altair1/pages/808.html
ファマイン,ほのお,はがね,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/811.html
イライラン,むし,でんき,PD,一般,,,https://w.atwiki.jp/altair1/pages/814.html
セトグオー,ノーマル,,PD,一般,,,https://w.atwiki.jp/altair1/pages/817.html
チェキッド,あく,ノーマル,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/819.html
チェキラス,あく,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/820.html
ララミンゴ,みず,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/822.html
パチリス,でんき,,DP,一般,,輝石,https://w.atwiki.jp/altair1/pages/823.html
パチリック,でんき,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/824.html
パンプッチ,くさ,フェアリー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/826.html
ルナビット,エスパー,,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/827.html
ルナバイン,エスパー,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/828.html
ウソギー,あく,,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/829.html
ウソドロ,あく,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/830.html
メタモン,ノーマル,,初代,除外,,,https://w.atwiki.jp/altair1/pages/831.html
オオムジナ,ノーマル,,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/833.html
ポコキング,ノーマル,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/834.html
カチコン,いわ,じめん,PD,一般,,,https://w.atwiki.jp/altair1/pages/835.html
ユキタテハ,むし,こおり,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/837.html
ペラップ,ノーマル,ひこう,DP,一般,,輝石,https://w.atwiki.jp/altair1/pages/838.html
オオペラー,エスパー,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/839.html
オリバー,ノーマル,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/840.html
ランペルン,ノーマル,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/841.html
キーボン,ノーマル,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/842.html
レディアン,むし,ひこう,金銀,一般,,輝石,https://w.atwiki.jp/altair1/pages/844.html
レディバル,むし,かくとう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/845.html
ハテナゼミ,むし,,PD,一般,,,https://w.atwiki.jp/altair1/pages/846.html
ケンタロス,ノーマル,,初代,一般,,,https://w.atwiki.jp/altair1/pages/848.html
ルナトーン,いわ,エスパー,RS,入手不可,,,https://w.atwiki.jp/altair1/pages/849.html
ソルロック,いわ,エスパー,RS,入手不可,,,https://w.atwiki.jp/altair1/pages/850.html
アスリスク,いわ,エスパー,AS,入手不可,,,https://w.atwiki.jp/altair1/pages/851.html
プラネム,いわ,エスパー,ベガ,入手不可,,,https://w.atwiki.jp/altair1/pages/852.html
コモラゴン,どく,ドラゴン,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/850.html
ドククラゲ,みず,どく,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/852.html
ヤミクラゲ,みず,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/853.html
オオイナリ,ほのお,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/855.html
ホムロソク,ほのお,ゴースト,ベガ,入手不可,,,
ガレキダマ,いわ,じめん,ベガ,入手不可,,,
ワラガシラ,でんき,ゴースト,ベガ,入手不可,,,
マルマイン,でんき,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/857.html
ドルマイン,でんき,,AS,一般,,,https://w.atwiki.jp/altair1/pages/858.html
ガラカサゴ,みず,どく,PD,一般,,,https://w.atwiki.jp/altair1/pages/860.html
スパイナー,みず,でんき,PD,一般,,,https://w.atwiki.jp/altair1/pages/861.html
バレッター,みず,はがね,PD,一般,,,https://w.atwiki.jp/altair1/pages/862.html
グラエナ,あく,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/864.html
ケルエナ,あく,,PD,一般,,,https://w.atwiki.jp/altair1/pages/865.html
スモーガス,どく,ほのお,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/867.html
カモドック,どく,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/869.html
トノッパー,むし,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/870.html
ガルラーダ,ひこう,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/871.html
ハサーガ,じめん,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/872.html
アメリシア,みず,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/874.html
カンカーン,ほのお,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/876.html
テイルーン,ゴースト,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/878.html
モグルトン,じめん,はがね,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/879.html
ツルボロス,くさ,ドラゴン,PD,一般,,,https://w.atwiki.jp/altair1/pages/881.html
フーピャン,くさ,はがね,PD,一般,,,https://w.atwiki.jp/altair1/pages/883.html
ラクチャン,ノーマル,,ベガ,除外,,,https://w.atwiki.jp/altair1/pages/884.html
ドゴン,かくとう,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/885.html
ヤミラミ,あく,ゴースト,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/886.html
トコヤミ,あく,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/887.html
クチート,はがね,フェアリー,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/888.html
クチールス,はがね,フェアリー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/889.html
ヤンデッド,くさ,どく,PD,一般,,,https://w.atwiki.jp/altair1/pages/891.html
カイロス,むし,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/892.html
ガッツロス,むし,じめん,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/893.html
アーボック,どく,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/895.html
アーボスク,どく,はがね,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/896.html
マタドガス,どく,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/898.html
モアドガス,どく,あく,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/899.html
コアラシ,くさ,いわ,PD,一般,,,https://w.atwiki.jp/altair1/pages/901.html
マグカルゴ,ほのお,いわ,金銀,一般,,輝石,https://w.atwiki.jp/altair1/pages/903.html
マグキガイ,ほのお,いわ,PD,一般,,,https://w.atwiki.jp/altair1/pages/904.html
ネオラント,みず,,DP,一般,,輝石,https://w.atwiki.jp/altair1/pages/906.html
テトライト,みず,,PD,一般,,,https://w.atwiki.jp/altair1/pages/907.html
パワホーン,かくとう,,PD,一般,,,https://w.atwiki.jp/altair1/pages/908.html
ジーランス,みず,いわ,RS,入手不可,,,
ダンカンス,みず,いわ,ベガ,入手不可,,,
ヒササビ,ほのお,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/913.html
テッコンボ,かくとう,いわ,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/915.html
ボンバット,じめん,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/916.html
ビークイン,むし,ひこう,DP,一般,,,https://w.atwiki.jp/altair1/pages/918.html
グランビー,むし,ひこう,PD,一般,,,https://w.atwiki.jp/altair1/pages/919.html
クソマルメ,むし,じめん,PD,一般,,,https://w.atwiki.jp/altair1/pages/910.html
ヒカラベ,むし,,PD,一般,,,https://w.atwiki.jp/altair1/pages/911.html
サンドパン,じめん,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/921.html
サンドリル,じめん,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/922.html
ビビッドン,でんき,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/923.html
オールガ,みず,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/925.html
ヒョウカク,こおり,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/926.html
サーナイト,エスパー,フェアリー,RS,一般,,,https://w.atwiki.jp/altair1/pages/929.html
エルレイド,エスパー,かくとう,DP,一般,,,https://w.atwiki.jp/altair1/pages/930.html
シルドール,エスパー,フェアリー,AS,一般,,,https://w.atwiki.jp/altair1/pages/932.html
セルディー,みず,こおり,ベガ,入手不可,,,
ギャラクシア,どく,エスパー,PD,一般,,,https://w.atwiki.jp/altair1/pages/933.html
ワークロ,むし,かくとう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/934.html
アリンセス,むし,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/935.html
カゼコンコ,どく,こおり,PD,一般,,,https://w.atwiki.jp/altair1/pages/936.html
ホネット,どく,,PD,一般,,,https://w.atwiki.jp/altair1/pages/937.html
ダイオーム,でんき,ドラゴン,PD,一般,,,https://w.atwiki.jp/altair1/pages/939.html
ドライアス,こおり,ドラゴン,PD,一般,,,https://w.atwiki.jp/altair1/pages/941.html
エリーター,ドラゴン,,PD,一般,,,https://w.atwiki.jp/altair1/pages/942.html
マスキッパ,くさ,,DP,一般,,輝石,https://w.atwiki.jp/altair1/pages/943.html
アルデッパ,くさ,みず,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/944.html
ゴキブロス,どく,むし,AS,一般,,輝石,https://w.atwiki.jp/altair1/pages/945.html
カミギリー,あく,むし,AS,一般,,,https://w.atwiki.jp/altair1/pages/946.html
ガネーシャ,エスパー,じめん,AS,一般,,,https://w.atwiki.jp/altair1/pages/948.html
ラブカス,みず,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/949.html
ラブリン,みず,ノーマル,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/950.html
ラプラス,みず,こおり,初代,入手不可,,,
サムラダケ,くさ,ほのお,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/952.html
テルテン,ノーマル,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/953.html
カクレオン,ノーマル,,RS,一般,,,https://w.atwiki.jp/altair1/pages/954.html
スリーパー,エスパー,,初代,一般,,輝石,https://w.atwiki.jp/altair1/pages/956.html
スリピット,エスパー,,PD,一般,,,https://w.atwiki.jp/altair1/pages/957.html
チリーン,エスパー,,RS,一般,,輝石,https://w.atwiki.jp/altair1/pages/959.html
カラコロン,エスパー,,PD,一般,,,https://w.atwiki.jp/altair1/pages/960.html
コータス,ほのお,,RS,入手不可,,,
デモリガン,あく,フェアリー,PD,一般/600族,,,https://w.atwiki.jp/altair1/pages/963.html
カソーダン,でんき,じめん,PD,一般/600族,,,https://w.atwiki.jp/altair1/pages/966.html
`;