window.customCsvData =`name,type1,type2,generation,filters,banFilter,styleForm,link
リーテイル,くさ,ひこう,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/73.html
ファマイン,ほのお,はがね,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/76.html
タテボーシ,みず,どく,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/167.html
オオスバメ,ノーマル,ひこう,RS,一般,,,https://w.atwiki.jp/altair1/pages/169.html
ルカリオ,かくとう,はがね,DP,一般,,,https://w.atwiki.jp/altair1/pages/171.html
ヘルガー,あく,ほのお,金銀,一般,,,https://w.atwiki.jp/altair1/pages/202.html
ダグトリオ,じめん,,初代,一般,,,https://w.atwiki.jp/altair1/pages/204.html
トゲキッス,ノーマル,ひこう,DP,一般,,,https://w.atwiki.jp/altair1/pages/207.html
フローリア,こおり,,AS,一般,,,https://w.atwiki.jp/altair1/pages/210.html
ライチュウ,でんき,,初代,一般,,,https://w.atwiki.jp/altair1/pages/214.html
ゴリチュウ,でんき,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/213.html
エアームド,はがね,ひこう,金銀,一般,,,https://w.atwiki.jp/altair1/pages/215.html
ニドクイン,どく,じめん,初代,一般,,,https://w.atwiki.jp/altair1/pages/218.html
ニドキング,どく,じめん,初代,一般,,,https://w.atwiki.jp/altair1/pages/221.html
フローゼル,みず,,DP,一般,,,https://w.atwiki.jp/altair1/pages/223.html
セラーナ,くさ,,AS,一般,,,https://w.atwiki.jp/altair1/pages/225.html
フォレトス,むし,はがね,金銀,一般,,,https://w.atwiki.jp/altair1/pages/227.html
パルシェン,みず,こおり,初代,一般,,,https://w.atwiki.jp/altair1/pages/229.html
ペガーン,エスパー,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/232.html
ユニサス,エスパー,はがね,AS,一般,,,https://w.atwiki.jp/altair1/pages/231.html
サワムラー,かくとう,,初代,一般,,,https://w.atwiki.jp/altair1/pages/234.html
エビワラー,かくとう,,初代,一般,,,https://w.atwiki.jp/altair1/pages/235.html
カポエラー,かくとう,,金銀,一般,,,https://w.atwiki.jp/altair1/pages/236.html
メタゲラス,はがね,じめん,AS,一般,,,https://w.atwiki.jp/altair1/pages/77.html
ディザソル,あく,,AS,一般,,,https://w.atwiki.jp/altair1/pages/239.html
フォリキー,ノーマル,エスパー,AS,一般,,,https://w.atwiki.jp/altair1/pages/241.html
ファントマ,ほのお,,AS,一般,,,https://w.atwiki.jp/altair1/pages/243.html
ジバコイル,でんき,はがね,DP,一般,,,https://w.atwiki.jp/altair1/pages/246.html
スターミー,みず,エスパー,初代,一般,,,https://w.atwiki.jp/altair1/pages/248.html
ゲンガー,ゴースト,どく,初代,一般,,,https://w.atwiki.jp/altair1/pages/251.html
ナッシー,くさ,エスパー,初代,一般,,,https://w.atwiki.jp/altair1/pages/253.html
ググズリー,ノーマル,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/255.html
ハンタマ,ゴースト,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/256.html
ドサイドン,じめん,いわ,DP,一般,,,https://w.atwiki.jp/altair1/pages/259.html
トロピウス,くさ,ひこう,RS,一般,,,https://w.atwiki.jp/altair1/pages/260.html
ポリゴンZ,ノーマル,,DP,一般,,,https://w.atwiki.jp/altair1/pages/263.html
トドゼルガ,こおり,みず,RS,一般,,,https://w.atwiki.jp/altair1/pages/266.html
マルマジロ,いわ,はがね,AS,一般,,,https://w.atwiki.jp/altair1/pages/268.html
リーフィス,くさ,みず,AS,一般,,,https://w.atwiki.jp/altair1/pages/270.html
ユキノオー,くさ,こおり,DP,一般,,,https://w.atwiki.jp/altair1/pages/272.html
ネクロシア,ゴースト,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/274.html
バフォット,はがね,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/277.html
ミルタンク,ノーマル,,金銀,一般,,,https://w.atwiki.jp/altair1/pages/278.html
ツボツボ,むし,いわ,金銀,封殺,,,https://w.atwiki.jp/altair1/pages/279.html
フィニクス,ほのお,ドラゴン,AS,一般,,,https://w.atwiki.jp/altair1/pages/282.html
コクジャク,エスパー,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/284.html
コーシャン,ほのお,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/286.html
ボルトック,でんき,,AS,一般,,,https://w.atwiki.jp/altair1/pages/288.html
テペトラー,みず,かくとう,AS,一般,,,https://w.atwiki.jp/altair1/pages/290.html
ロップル,ゴースト,エスパー,AS,一般,,,https://w.atwiki.jp/altair1/pages/291.html
ニートン,ゴースト,,AS,一般,,,https://w.atwiki.jp/altair1/pages/294.html
ヨルノズク,ノーマル,ひこう,金銀,一般,,,https://w.atwiki.jp/altair1/pages/296.html
ハクタクン,エスパー,,AS,一般,,,https://w.atwiki.jp/altair1/pages/297.html
エレキブル,でんき,,DP,一般,,,https://w.atwiki.jp/altair1/pages/300.html
ブーバーン,ほのお,,DP,一般,,,https://w.atwiki.jp/altair1/pages/303.html
ガルーラ,ノーマル,,初代,一般,,,https://w.atwiki.jp/altair1/pages/304.html
ユレイドル,いわ,くさ,RS,一般,,,https://w.atwiki.jp/altair1/pages/306.html
マカドゥス,いわ,でんき,AS,一般,,,https://w.atwiki.jp/altair1/pages/308.html
プテラ,いわ,ひこう,初代,一般,,,https://w.atwiki.jp/altair1/pages/309.html
バンギラス,いわ,あく,金銀,600族,,,https://w.atwiki.jp/altair1/pages/312.html
メタグロス,はがね,エスパー,RS,600族,,,https://w.atwiki.jp/altair1/pages/315.html
ガブリアス,ドラゴン,じめん,DP,600族,,,https://w.atwiki.jp/altair1/pages/318.html
ドラドーン,ドラゴン,ひこう,AS,600族,,,https://w.atwiki.jp/altair1/pages/321.html
フリーザー,こおり,ひこう,初代,準伝説,,,https://w.atwiki.jp/altair1/pages/322.html
サンダー,でんき,ひこう,初代,準伝説,,,https://w.atwiki.jp/altair1/pages/323.html
ファイヤー,ほのお,ひこう,初代,準伝説,,,https://w.atwiki.jp/altair1/pages/324.html
ライコウ,でんき,,金銀,準伝説,,,https://w.atwiki.jp/altair1/pages/325.html
エンテイ,ほのお,,金銀,準伝説,,,https://w.atwiki.jp/altair1/pages/326.html
スイクン,みず,,金銀,準伝説,,,https://w.atwiki.jp/altair1/pages/327.html
ライラプス,じめん,,AS,準伝説,,,https://w.atwiki.jp/altair1/pages/328.html
ガニメデ,ひこう,,AS,準伝説,,,https://w.atwiki.jp/altair1/pages/329.html
ネメア,はがね,,AS,準伝説,,,https://w.atwiki.jp/altair1/pages/330.html
ディアルガ,はがね,ドラゴン,DP,禁止級,,,https://w.atwiki.jp/altair1/pages/331.html
パルキア,みず,ドラゴン,DP,禁止級,,,https://w.atwiki.jp/altair1/pages/332.html
ダークライ,あく,,DP,幻,,,https://w.atwiki.jp/altair1/pages/333.html
ルギア,エスパー,ひこう,金銀,禁止級,,,https://w.atwiki.jp/altair1/pages/334.html
ホウオウ,ほのお,ひこう,金銀,禁止級,,,https://w.atwiki.jp/altair1/pages/335.html
ミュウツー,エスパー,,初代,禁止級,,,https://w.atwiki.jp/altair1/pages/336.html
ミュウ,エスパー,,初代,幻,,,https://w.atwiki.jp/altair1/pages/337.html
フシギバナ,くさ,どく,初代,一般/御三家,,,https://w.atwiki.jp/altair1/pages/340.html
リザードン,ほのお,ひこう,初代,一般/御三家,,,https://w.atwiki.jp/altair1/pages/343.html
カメックス,みず,,初代,一般/御三家,,,https://w.atwiki.jp/altair1/pages/346.html
バジリール,くさ,でんき,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/349.html
コマレオン,ほのお,じめん,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/352.html
バクソウオ,みず,ゴースト,AS,一般/御三家,,,https://w.atwiki.jp/altair1/pages/355.html
チェキッド,あく,ノーマル,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/357.html
チェキラス,あく,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/358.html
ララミンゴ,みず,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/360.html
パチリック,でんき,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/362.html
パンプッチ,くさ,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/364.html
ルナバイン,エスパー,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/366.html
ウソドロ,あく,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/394.html
メタモン,ノーマル,,初代,除外,,,https://w.atwiki.jp/altair1/pages/395.html
レジュリア,こおり,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/398.html
ポコキング,ノーマル,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/401.html
アスイーツ,こおり,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/402.html
ユキタテハ,むし,こおり,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/404.html
オオペラー,エスパー,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/406.html
オリバー,ノーマル,,AS,一般,,,https://w.atwiki.jp/altair1/pages/407.html
ランペルン,ノーマル,,AS,一般,,,https://w.atwiki.jp/altair1/pages/408.html
キーボン,ノーマル,,AS,一般,,,https://w.atwiki.jp/altair1/pages/409.html
レディバル,むし,かくとう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/412.html
アンノーン,エスパー,,金銀,除外,,,https://w.atwiki.jp/altair1/pages/413.html
ケンタロス,ノーマル,,初代,一般,,,https://w.atwiki.jp/altair1/pages/415.html
プラネム,いわ,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/419.html
コモラゴン,どく,ドラゴン,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/421.html
オクタン,みず,,金銀,一般,,,https://w.atwiki.jp/altair1/pages/423.html
ヤミクラゲ,みず,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/426.html
オオイナリ,ほのお,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/428.html
ホムロソク,ほのお,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/430.html
ガレキダマ,いわ,じめん,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/431.html
ジバクン,ノーマル,ゴースト,ベガ,禁止級,,,https://w.atwiki.jp/altair1/pages/432.html
ワラガシラ,ゴースト,でんき,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/434.html
ドルマイン,でんき,,AS,Tier1,,,https://w.atwiki.jp/altair1/pages/437.html
ドンカラス,あく,ひこう,DP,一般,,,https://w.atwiki.jp/altair1/pages/439.html
バクオング,ノーマル,,RS,一般,,,https://w.atwiki.jp/altair1/pages/442.html
キングラー,みず,,初代,一般,,,https://w.atwiki.jp/altair1/pages/444.html
スモーガス,どく,ほのお,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/446.html
カモドック,どく,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/448.html
トノッパー,むし,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/449.html
ガルラーダ,ひこう,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/450.html
ハサーガ,じめん,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/451.html
アメリシア,みず,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/452.html
カンカーン,ほのお,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/455.html
テイルーン,ゴースト,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/457.html
モグルトン,じめん,はがね,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/458.html
マニューラ,あく,こおり,DP,一般,,,https://w.atwiki.jp/altair1/pages/460.html
キノガッサ,くさ,かくとう,RS,封殺,,,https://w.atwiki.jp/altair1/pages/462.html
ラクチャン,ノーマル,,ベガ,除外,,,https://w.atwiki.jp/altair1/pages/463.html
ドゴン,かくとう,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/464.html
トコヤミ,あく,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/466.html
クチールス,はがね,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/468.html
ハッサム,むし,はがね,金銀,一般,,,https://w.atwiki.jp/altair1/pages/470.html
ガッツロス,むし,じめん,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/472.html
アーボスク,どく,はがね,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/475.html
モアドガス,どく,あく,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/478.html
ヨノワール,ゴースト,,DP,一般,,,https://w.atwiki.jp/altair1/pages/481.html
ベロベルト,ノーマル,,DP,一般,,,https://w.atwiki.jp/altair1/pages/483.html
アリアドス,むし,どく,金銀,一般,,,https://w.atwiki.jp/altair1/pages/485.html
デンチュラ,むし,でんき,BW,一般,,,https://w.atwiki.jp/altair1/pages/487.html
ベタデーム,みず,ほのお,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/489.html
ダンカンス,みず,いわ,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/491.html
ヒササビ,ほのお,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/493.html
ドサーモン,みず,じめん,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/495.html
テッコンボ,かくとう,いわ,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/497.html
ボンバット,じめん,ゴースト,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/498.html
ハピナス,ノーマル,,金銀,封殺,,,https://w.atwiki.jp/altair1/pages/501.html
テッカニン,むし,ひこう,RS,一般,,,https://w.atwiki.jp/altair1/pages/503.html
ヌケニン,むし,ゴースト,RS,除外,,,https://w.atwiki.jp/altair1/pages/504.html
サンドリル,じめん,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/506.html
ビビッドン,でんき,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/511.html
オールガ,みず,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/509.html
ヒョウカク,こおり,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/508.html
サーナイト,エスパー,,RS,一般,,,https://w.atwiki.jp/altair1/pages/514.html
エルレイド,エスパー,かくとう,DP,一般,,,https://w.atwiki.jp/altair1/pages/515.html
シルドール,エスパー,,AS,封殺,,,https://w.atwiki.jp/altair1/pages/517.html
セルディー,みず,こおり,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/529.html
バーネッコ,くさ,じめん,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/531.html
ヒカリゴケ,くさ,でんき,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/533.html
フリージオ,こおり,,BW,一般,,,https://w.atwiki.jp/altair1/pages/534.html
ワークロ,むし,かくとう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/536.html
アリンセス,むし,エスパー,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/537.html
ゴローニャ,いわ,じめん,初代,一般,,,https://w.atwiki.jp/altair1/pages/535.html
ドラピオン,どく,あく,DP,一般,,,https://w.atwiki.jp/altair1/pages/541.html
オンネット,ゴースト,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/544.html
マンムー,こおり,じめん,DP,一般,,,https://w.atwiki.jp/altair1/pages/547.html
マッギョ,じめん,でんき,BW,一般,,,https://w.atwiki.jp/altair1/pages/548.html
パッチール,ノーマル,,RS,一般,,,https://w.atwiki.jp/altair1/pages/549.html
アルデッパ,くさ,みず,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/551.html
カミギリー,あく,むし,AS,一般,,,https://w.atwiki.jp/altair1/pages/553.html
ガネーシャ,エスパー,じめん,AS,一般,,,https://w.atwiki.jp/altair1/pages/555.html
ギギギアル,はがね,,BW,一般,,,https://w.atwiki.jp/altair1/pages/558.html
ラブリン,みず,ノーマル,ベガ,Tier1,,,https://w.atwiki.jp/altair1/pages/561.html
ラプラス,みず,こおり,初代,一般,,,https://w.atwiki.jp/altair1/pages/560.html
サムラダケ,くさ,ほのお,ベガ,封殺,,,https://w.atwiki.jp/altair1/pages/564.html
ノクタス,くさ,あく,RS,一般,,,https://w.atwiki.jp/altair1/pages/566.html
プテリクス,いわ,ひこう,AS,一般,,,https://w.atwiki.jp/altair1/pages/568.html
ティラノス,いわ,あく,AS,一般,,,https://w.atwiki.jp/altair1/pages/569.html
ブレイドン,はがね,いわ,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/571.html
ブレイオー,はがね,かくとう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/572.html
テルテン,ノーマル,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/518.html
イワパレス,むし,いわ,BW,一般,,,https://w.atwiki.jp/altair1/pages/520.html
ナットレイ,くさ,はがね,BW,封殺,,,https://w.atwiki.jp/altair1/pages/522.html
シビルドン,でんき,,BW,一般,,,https://w.atwiki.jp/altair1/pages/525.html
プレゼンタ,こおり,ひこう,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/527.html
ストータス,ほのお,いわ,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/368.html
ノコウテイ,ノーマル,,ベガ,一般,,,https://w.atwiki.jp/altair1/pages/370.html
カモナイツ,かくとう,ひこう,ベガ,Tier1,,,https://w.atwiki.jp/altair1/pages/372.html
ズルズキン,あく,かくとう,BW,一般,,,https://w.atwiki.jp/altair1/pages/374.html
ドレディア,くさ,,BW,一般,,,https://w.atwiki.jp/altair1/pages/376.html
コジョンド,かくとう,,BW,一般,,,https://w.atwiki.jp/altair1/pages/378.html
ワルビアル,じめん,あく,BW,一般,,,https://w.atwiki.jp/altair1/pages/379.html
ロイツァー,ノーマル,ドラゴン,ベガ,準伝説,,,https://w.atwiki.jp/altair1/pages/382.html
ガタノア,あく,ドラゴン,ベガ,準伝説,,,https://w.atwiki.jp/altair1/pages/383.html
ヒードラン,ほのお,はがね,DP,準伝説,,,https://w.atwiki.jp/altair1/pages/385.html
ラティアス,ドラゴン,エスパー,RS,準伝説,,,https://w.atwiki.jp/altair1/pages/386.html
ラティオス,ドラゴン,エスパー,RS,準伝説,,,https://w.atwiki.jp/altair1/pages/387.html
フィオネ,みず,,DP,一般,,,https://w.atwiki.jp/altair1/pages/388.html
マナフィ,みず,,DP,幻,,,https://w.atwiki.jp/altair1/pages/389.html
オルディナ,ゴースト,,AS,幻,,,https://w.atwiki.jp/altair1/pages/390.html
オルマリア,ゴースト,,ベガ,禁止級,,,https://w.atwiki.jp/altair1/pages/391.html
アスフィア,ほのお,ドラゴン,ベガ,禁止級,,,https://w.atwiki.jp/altair1/pages/392.html
`;